[ 2023-11-02 22:27:17,286 ] 241 django.request - ERROR - Internal Server Error: /team_summary/
Traceback (most recent call last):
  File "E:\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\django_project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "E:\django_project\match_tournament\tournament\views.py", line 64, in get_queryset
    matches_won=Count(Case(When(team_matches__batting_score__gt=F('team_matches__batting_score'),
NameError: name 'F' is not defined
[ 2023-11-02 22:27:19,281 ] 241 django.request - ERROR - Internal Server Error: /team_summary/
Traceback (most recent call last):
  File "E:\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\django_project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "E:\django_project\match_tournament\tournament\views.py", line 64, in get_queryset
    matches_won=Count(Case(When(team_matches__batting_score__gt=F('team_matches__batting_score'),
NameError: name 'F' is not defined
[ 2023-11-02 22:27:20,247 ] 241 django.request - ERROR - Internal Server Error: /team_summary/
Traceback (most recent call last):
  File "E:\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\django_project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "E:\django_project\match_tournament\tournament\views.py", line 64, in get_queryset
    matches_won=Count(Case(When(team_matches__batting_score__gt=F('team_matches__batting_score'),
NameError: name 'F' is not defined
[ 2023-11-02 22:27:20,940 ] 241 django.request - ERROR - Internal Server Error: /team_summary/
Traceback (most recent call last):
  File "E:\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\django_project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "E:\django_project\match_tournament\tournament\views.py", line 64, in get_queryset
    matches_won=Count(Case(When(team_matches__batting_score__gt=F('team_matches__batting_score'),
NameError: name 'F' is not defined
[ 2023-11-02 22:27:22,071 ] 241 django.request - ERROR - Internal Server Error: /team_summary/
Traceback (most recent call last):
  File "E:\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\django_project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\django_project\env\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "E:\django_project\match_tournament\tournament\views.py", line 64, in get_queryset
    matches_won=Count(Case(When(team_matches__batting_score__gt=F('team_matches__batting_score'),
NameError: name 'F' is not defined
[ 2023-11-02 22:28:02,711 ] 266 django.utils.autoreload - INFO - E:\django_project\match_tournament\tournament\views.py changed, reloading.
